### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by nobodyshere** [nobodyshere/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by greedydwarf222** [comment]
https://twitter.com/yanukovitch
realPresidentOfUkraine@mail.ru
https://www.instagram.com/yanukovichviktor/
https://www.president.gov.ua/ (тимчасово не працює)
